# Generated by Django 5.1.7 on 2025-03-21 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('informacion_facturacion', models.TextField(blank=True, null=True)),
                ('estado_verificacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('verificado', 'Verificado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('documento_rut', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('documento_cedula', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('contrato_firmado', models.FileField(blank=True, null=True, upload_to='contratos/')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('especificaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('alquilado', 'En alquiler'), ('reservado', 'Reservado')], default='disponible', max_length=20)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_alquiler', models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('renovacion', models.BooleanField(default=False)),
                ('aprobado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('contrato_firmado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.cliente')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contratacion', models.DateField(auto_now_add=True)),
                ('terminos_contrato', models.TextField()),
                ('fecha_firma', models.DateField(blank=True, null=True)),
                ('documento_contrato', models.FileField(upload_to='contratos/')),
                ('alquiler', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alquiler.alquiler')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('efectivo', 'Efectivo')], max_length=20)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('parcial', 'Parcial')], max_length=20)),
                ('factura_generada', models.BooleanField(default=False)),
                ('referencia_transaccion', models.CharField(blank=True, max_length=100, null=True)),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.alquiler')),
            ],
        ),
    ]
