# Generated by Django 5.1.7 on 2025-06-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='numero_factura',
            field=models.CharField(blank=True, help_text='Dejar en blanco para reservas', max_length=20, null=True, unique=True),
        ),
    ]
