# Generated by Django 5.1.7 on 2025-07-25 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='id',
            new_name='uuid_id',
        ),
    ]
