# Generated by Django 5.1.7 on 2025-07-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activation_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
