# Generated by Django 5.1.7 on 2025-03-25 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alquiler.rol'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vencimiento', 'Recordatorio de Vencimiento'), ('pago', 'Recordatorio de Pago'), ('reserva', 'Aviso de Reserva'), ('general', 'Otro')], max_length=20)),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('fallida', 'Fallida')], default='pendiente', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='alquiler.cliente')),
            ],
        ),
    ]
