# Generated by Django 5.1.7 on 2025-06-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0002_alter_alquiler_numero_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='es_reserva',
            field=models.BooleanField(default=False),
        ),
    ]
