# Generated by Django 5.1.7 on 2025-03-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0002_alter_alquiler_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='estado_alquiler',
            field=models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('reservado', 'Reservado')], default='activo', max_length=20),
        ),
    ]
