# Generated by Django 5.1.7 on 2025-07-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0002_usuario_activation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activation_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
