# Generated by Django 5.1.7 on 2025-03-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0003_alter_alquiler_estado_alquiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='firma_cliente',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
    ]
