# Generated by Django 5.1.7 on 2025-03-25 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0003_ordencompra_itemordencompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='ItemOrdenCompra',
        ),
        migrations.DeleteModel(
            name='OrdenCompra',
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
