# Generated by Django 5.1.7 on 2025-06-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0003_alquiler_es_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='es_reserva',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='estado_alquiler',
            field=models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('reservado', 'Reservado'), ('pendiente_aprobacion', 'Pendiente de Aprobación')], default='pendiente_aprobacion', max_length=20),
        ),
    ]
