# Generated by Django 5.1.7 on 2025-05-13 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0004_remove_notificacion_cliente_delete_itemordencompra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.rol'),
        ),
    ]
