# Generated by Django 5.1.7 on 2025-06-25 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0004_alter_alquiler_es_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='alquiler',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='alquiler.alquiler'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='documento_contrato',
            field=models.FileField(blank=True, null=True, upload_to='contratos/'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='terminos_contrato',
            field=models.TextField(blank=True, null=True),
        ),
    ]
