# Generated by Django 5.1.7 on 2025-07-13 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0004_rol_grupo_rol_permisos'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'ordering': ['nombre_rol'], 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nombre_usuario'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='rol',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='grupo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Grupo asociado'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre_rol',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre del Rol'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(blank=True, related_name='roles', to='auth.permission', verbose_name='Permisos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='activation_token',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Token de activación'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='activation_token_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha creación token'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cliente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alquiler.cliente', verbose_name='Cliente asociado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado_usuario',
            field=models.CharField(default='activo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Acceso administración'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='alquiler.rol', verbose_name='Rol asignado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ultimo_acceso',
            field=models.DateTimeField(auto_now=True, verbose_name='Último acceso'),
        ),
    ]
