# Generated by Django 5.1.7 on 2025-06-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0005_alter_contrato_alquiler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='firma_representante',
            field=models.ImageField(blank=True, null=True, upload_to='firmas_representante/'),
        ),
    ]
