# Generated by Django 5.1.7 on 2025-07-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0005_alter_rol_options_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoequipo',
            name='foto',
            field=models.ImageField(blank=True, help_text='Suba una foto del equipo', null=True, upload_to='fotos_equipos/', verbose_name='Archivo de imagen'),
        ),
    ]
