# Generated by Django 5.1.7 on 2025-07-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0006_alter_fotoequipo_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alquiler',
            old_name='precio_subtotal',
            new_name='precio_sin_iva',
        ),
        migrations.RemoveField(
            model_name='detallealquiler',
            name='precio_total',
        ),
        migrations.AddField(
            model_name='alquiler',
            name='con_iva',
            field=models.BooleanField(default=True, verbose_name='Incluir IVA (19%)'),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='detallealquiler',
            name='numeros_serie',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
