# Generated by Django 5.1.7 on 2025-06-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0006_contrato_firma_representante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='es_reserva',
            field=models.BooleanField(default=False),
        ),
    ]
