# Generated by Django 5.1.7 on 2025-05-16 16:04

import alquiler.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0006_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(help_text='Suba una foto del equipo', upload_to=alquiler.models.equipo_foto_upload_path, verbose_name='Archivo de imagen')),
                ('es_principal', models.BooleanField(default=False, help_text='Marcar si esta es la foto principal del equipo', verbose_name='Foto principal')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Foto de equipo',
                'verbose_name_plural': 'Fotos de equipos',
                'ordering': ['-es_principal', 'fecha_subida'],
            },
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['marca', 'modelo'], 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AddField(
            model_name='equipo',
            name='descripcion_larga',
            field=models.TextField(blank=True, help_text='Descripción completa con formato HTML permitido', null=True, verbose_name='Descripción detallada'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='es_html',
            field=models.BooleanField(default=False, help_text='Marcar si la descripción contiene formato HTML', verbose_name='Usar HTML'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='valoracion_promedio',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Valoración promedio'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('alquilado', 'En alquiler'), ('reservado', 'Reservado'), ('mantenimiento', 'En mantenimiento')], default='disponible', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='equipo',
            constraint=models.CheckConstraint(condition=models.Q(('valoracion_promedio__gte', 0.0), ('valoracion_promedio__lte', 5.0)), name='valoracion_promedio_rango'),
        ),
        migrations.AddField(
            model_name='fotoequipo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='alquiler.equipo', verbose_name='Equipo asociado'),
        ),
    ]
