# Generated by Django 5.1.7 on 2025-07-16 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0007_rename_precio_subtotal_alquiler_precio_sin_iva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alquileres_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='renovacion_automatica',
            field=models.BooleanField(default=False, verbose_name='Renovación automática'),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='con_iva',
            field=models.BooleanField(default=True, verbose_name='Incluye IVA'),
        ),
    ]
