# Generated by Django 5.1.7 on 2025-06-28 16:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0007_alter_alquiler_es_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrega', 'Acta de Entrega'), ('devolucion', 'Acta de Devolución')], max_length=10)),
                ('archivo', models.FileField(upload_to='actas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('numero_acta', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actas', to='alquiler.alquiler')),
            ],
            options={
                'verbose_name': 'Acta',
                'verbose_name_plural': 'Actas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
