# Generated by Django 5.1.7 on 2025-05-20 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0007_fotoequipo_alter_equipo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='cantidad_disponible',
            field=models.PositiveIntegerField(default=1, help_text='Número de unidades disponibles para alquiler', verbose_name='Cantidad disponible'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='cantidad_total',
            field=models.PositiveIntegerField(default=1, help_text='Número total de unidades idénticas de este equipo', verbose_name='Cantidad total'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='precio_anio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de alquiler por un año (365 días)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio por año'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='precio_dia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='equipo',
            name='precio_mes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de alquiler por un mes (30 días)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio por mes'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='precio_semana',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de alquiler por una semana (7 días)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio por semana'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='precio_semestre',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de alquiler por seis meses (180 días)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio por semestre'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='precio_trimestre',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de alquiler por tres meses (90 días)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio por trimestre'),
        ),
        migrations.AddConstraint(
            model_name='equipo',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_disponible__lte', models.F('cantidad_total'))), name='cantidad_disponible_no_mayor_total'),
        ),
        migrations.AddConstraint(
            model_name='equipo',
            constraint=models.CheckConstraint(condition=models.Q(('precio_dia__gte', 0)), name='precio_dia_positivo'),
        ),
        migrations.AddConstraint(
            model_name='equipo',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_total__gte', 0)), name='cantidad_total_positiva'),
        ),
    ]
