# Generated by Django 5.1.7 on 2025-06-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0008_acta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
