# Generated by Django 5.1.7 on 2025-05-23 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0008_equipo_cantidad_disponible_equipo_cantidad_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alquileres', to='alquiler.cliente'),
        ),
    ]
