# Generated by Django 5.1.7 on 2025-07-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0008_alquiler_creado_por_alquiler_renovacion_automatica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio Total'),
        ),
    ]
