# Generated by Django 5.1.7 on 2025-05-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0009_alter_alquiler_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='precio_total',
            field=models.IntegerField(),
        ),
    ]
