# Generated by Django 5.1.7 on 2025-07-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0010_alter_detallealquiler_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='requiere_serie',
            field=models.BooleanField(default=True, help_text='Marcar si este equipo requiere registrar número de serie', verbose_name='Requiere número de serie'),
        ),
    ]
