# Generated by Django 5.1.7 on 2025-06-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0010_alter_pago_options_pago_aprobado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
