# Generated by Django 5.1.7 on 2025-05-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0010_alter_alquiler_precio_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='barrio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='metodo_pago_preferido',
            field=models.CharField(blank=True, choices=[('transferencia', 'Transferencia Bancaria'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('tarjeta', 'Tarjeta de crédito/débito'), ('efectivo', 'Efectivo')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('natural', 'Persona Natural'), ('juridica', 'Persona Jurídica')], default='natural', max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('NIT', 'Número de Identificación Tributaria'), ('PAS', 'Pasaporte')], default='CC', max_length=3),
        ),
    ]
