# Generated by Django 5.1.7 on 2025-07-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0011_equipo_requiere_serie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alquiler',
            old_name='precio_sin_iva',
            new_name='precio_subtotal',
        ),
        migrations.RemoveField(
            model_name='alquiler',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='requiere_serie',
        ),
        migrations.AddField(
            model_name='detallealquiler',
            name='precio_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='con_iva',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='numero_factura',
            field=models.CharField(blank=True, help_text='Dejar en blanco para reservas', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='renovacion_automatica',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detallealquiler',
            name='numeros_serie',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='detallealquiler',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
