# Generated by Django 5.1.7 on 2025-06-29 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0011_alquiler_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alquiler',
            name='total',
        ),
    ]
