# Generated by Django 5.1.7 on 2025-05-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0011_cliente_barrio_cliente_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('natural', 'Persona Natural'), ('juridica', 'Persona Jurídica')], default='Natural', max_length=10),
        ),
    ]
