# Generated by Django 5.1.7 on 2025-07-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0012_rename_precio_sin_iva_alquiler_precio_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallealquiler',
            name='con_iva',
            field=models.BooleanField(default=True, verbose_name='Aplica IVA'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='requiere_serie',
            field=models.BooleanField(default=True, verbose_name='Requiere número de serie'),
        ),
    ]
