# Generated by Django 5.1.7 on 2025-07-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0013_detallealquiler_con_iva_equipo_requiere_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='sku',
            field=models.CharField(blank=True, help_text='Código único de identificación del equipo', max_length=50, null=True, unique=True, verbose_name='SKU'),
        ),
    ]
