# Generated by Django 5.1.7 on 2025-07-10 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0013_userauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affected_by_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userauditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Inicio de sesión'), ('login_failed', 'Intento fallido de login'), ('logout', 'Cierre de sesión'), ('password_change', 'Cambio de contraseña'), ('password_reset', 'Restablecimiento de contraseña'), ('user_edit', 'Edición de perfil'), ('user_create', 'Creación de usuario'), ('user_delete', 'Eliminación de usuario'), ('role_change', 'Cambio de rol'), ('status_change', 'Cambio de estado (activar/desactivar)'), ('permission_change', 'Cambio de permisos'), ('data_access', 'Acceso a datos sensibles'), ('config_change', 'Cambio de configuración'), ('export_data', 'Exportación de datos')], max_length=50),
        ),
    ]
