# Generated by Django 5.1.7 on 2025-05-27 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0013_alquiler_fecha_creacion_alquiler_numero_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros_serie', to='alquiler.equipo')),
            ],
            options={
                'verbose_name': 'Número de serie',
                'verbose_name_plural': 'Números de serie',
            },
        ),
    ]
