# Generated by Django 5.1.7 on 2025-07-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0014_userauditlog_target_user_alter_userauditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Inicio de sesión'), ('login_failed', 'Intento fallido de login'), ('logout', 'Cierre de sesión'), ('password_change', 'Cambio de contraseña'), ('password_reset', 'Restablecimiento de contraseña'), ('user_edit', 'Edición de perfil'), ('user_create', 'Creación de usuario'), ('user_delete', 'Eliminación de usuario'), ('role_change', 'Cambio de rol'), ('status_change', 'Cambio de estado'), ('permission_change', 'Cambio de permisos'), ('data_access', 'Acceso a datos sensibles'), ('config_change', 'Cambio de configuración'), ('export_data', 'Exportación de datos')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userauditlog',
            name='status',
            field=models.CharField(choices=[('success', 'Exitoso'), ('failed', 'Fallido'), ('warning', 'Advertencia')], default='success', max_length=20),
        ),
    ]
