# Generated by Django 5.1.7 on 2025-07-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0014_equipo_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estudio_credito',
            field=models.FileField(blank=True, help_text='Documento del estudio de crédito del cliente', null=True, upload_to='estudios_credito/', verbose_name='Estudio de crédito'),
        ),
    ]
