# Generated by Django 5.1.7 on 2025-05-27 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0014_numeroserie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='numero_serie',
        ),
        migrations.CreateModel(
            name='SerialEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seriales', to='alquiler.equipo')),
            ],
        ),
        migrations.DeleteModel(
            name='NumeroSerie',
        ),
    ]
