# Generated by Django 5.1.7 on 2025-07-10 18:09

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0015_alter_userauditlog_action_alter_userauditlog_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userauditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Registro de auditoría', 'verbose_name_plural': 'Registros de auditoría'},
        ),
        migrations.AlterField(
            model_name='userauditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Inicio de sesión'), ('login_failed', 'Intento fallido de login'), ('logout', 'Cierre de sesión'), ('password_change', 'Cambio de contraseña'), ('password_reset', 'Restablecimiento de contraseña'), ('user_edit', 'Edición de perfil'), ('user_create', 'Creación de usuario'), ('user_delete', 'Eliminación de usuario'), ('role_change', 'Cambio de rol'), ('status_change', 'Cambio de estado'), ('permission_change', 'Cambio de permisos'), ('data_access', 'Acceso a datos sensibles'), ('config_change', 'Cambio de configuración'), ('export_data', 'Exportación de datos'), ('admin_action', 'Acción administrativa')], max_length=50, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='userauditlog',
            name='details',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Detalles'),
        ),
        migrations.AlterField(
            model_name='userauditlog',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='Dirección IP'),
        ),
        migrations.AlterField(
            model_name='userauditlog',
            name='status',
            field=models.CharField(choices=[('success', 'Exitoso'), ('failed', 'Fallido'), ('warning', 'Advertencia')], default='success', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='userauditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affected_by_actions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario objetivo'),
        ),
        migrations.AlterField(
            model_name='userauditlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='userauditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='userauditlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='Agente de usuario'),
        ),
        migrations.AddIndex(
            model_name='userauditlog',
            index=models.Index(fields=['-timestamp'], name='alquiler_us_timesta_e6fe31_idx'),
        ),
        migrations.AddIndex(
            model_name='userauditlog',
            index=models.Index(fields=['user', 'timestamp'], name='alquiler_us_user_id_c725eb_idx'),
        ),
        migrations.AddIndex(
            model_name='userauditlog',
            index=models.Index(fields=['action', 'status'], name='alquiler_us_action_648ea2_idx'),
        ),
    ]
