# Generated by Django 5.1.7 on 2025-07-17 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0015_cliente_estudio_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='alquiler.cliente'),
        ),
    ]
