# Generated by Django 5.1.7 on 2025-07-17 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0016_pago_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='alquiler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alquiler.alquiler'),
        ),
    ]
