# Generated by Django 5.1.7 on 2025-07-18 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0017_alter_pago_alquiler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='pago',
            name='alquiler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='alquiler.alquiler'),
        ),
    ]
