# Generated by Django 5.1.7 on 2025-07-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0018_remove_pago_cliente_alter_pago_alquiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_bloqueo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='motivo_bloqueo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='deuda_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
