# Generated by Django 5.1.7 on 2025-07-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0019_cliente_bloqueado_cliente_fecha_bloqueo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='bloqueado',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_bloqueo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='motivo_bloqueo',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='deuda_total',
            field=models.IntegerField(default=0),
        ),
    ]
