# Generated by Django 5.1.7 on 2025-07-21 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0020_remove_cliente_bloqueado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alquileres', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador'),
        ),
    ]
