# Generated by Django 5.1.7 on 2025-07-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0021_alquiler_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alquiler',
            name='usuario',
        ),
    ]
