# Generated by Django 5.1.7 on 2025-07-23 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0022_remove_alquiler_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alquileres_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
